name: rebuild webpages

on: workflow_dispatch

permissions:
  contents: write

jobs:
  rebuild_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute main.py
        run: |
          cd 'Stock Forecasting'
          python main.py
      - name: Commit changes
        run: |
          echo $pwd
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m 'Updated via workflow bot'
          git push